---
spring:
  profiles: default
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  dataSource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/inventory
    username: server
    password: server
    
    
    

---
# ejecutar en la caprtea target
# java -jar -Dspring.profiles.active=desarrollo inventoryApiRest-0.0.1-SNAPSHOT.jar
# ejecutar donde esta el pom.xml
# mvn spring-boot:run -Drun.jvmArguments="-Dspring.profiles.active=desarrollo"    

spring:
  profiles: desarrollo
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  dataSource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/inventorydesarrollo
    username: root
    password: root
    
---
spring:
  profiles: produccion
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  dataSource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/inventoryproduccion
    username: produccion
    password: produccion
